[supervisord]
nodaemon=true
user=root
logfile=/opt/udp-bridge/logs/supervisord.log
pidfile=/var/run/supervisord.pid
loglevel=info

[program:sshd]
command=/usr/sbin/sshd -D
stdout_logfile=/opt/udp-bridge/logs/sshd.log
stderr_logfile=/opt/udp-bridge/logs/sshd_error.log
autorestart=true
priority=100

[program:udp2tcp_srv]
command=/usr/local/bin/udp2tcp_srv /opt/udp-bridge/udp2tcp_srv.yaml
directory=/opt/udp-bridge
stdout_logfile=/opt/udp-bridge/logs/udp2tcp_srv.log
stderr_logfile=/opt/udp-bridge/logs/udp2tcp_srv_error.log
autorestart=true
priority=200
environment=UDP2TCP_LOG_LEVEL="%(ENV_LOG_LEVEL)s"

[unix_http_server]
file=/var/run/supervisor.sock

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface
