plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.sshtunnel'
    compileSdk 34
    
    defaultConfig {
        applicationId "com.example.sshtunnel"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
        
        ndk {
            abiFilters "arm64-v8a", "armeabi-v7a", "x86", "x86_64"
        }
        
        externalNativeBuild {
            cmake {
                // Требуется C++20 для библиотеки udp2tcp
                cppFlags "-std=c++20"
                arguments "-DANDROID_STL=c++_shared", "-DUSE_UDP2TCP=ON", "-DUDP2TCP_ENABLE_C_API=ON", "-DBUILD_TESTING=OFF"
            }
        }
    }
    
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    
    externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
        }
    }
    
    ndkVersion "29.0.13846066"
    
    packaging {
        pickFirst '**/libc++_shared.so'
        pickFirst '**/libjsc.so'
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.coordinatorlayout:coordinatorlayout:1.2.0'
    implementation 'androidx.core:core:1.12.0'
    implementation 'com.google.code.gson:gson:2.10.1'
}